# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sawyer_control.v1 import control_pb2 as sawyer__control_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sawyer_control/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Health',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.HealthRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.HealthReply.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/GetState',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.RobotState.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/sawyer.control.v1.RobotControl/StreamState',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.StreamStateRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.RobotState.FromString,
                _registered_method=True)
        self.GetPose = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/GetPose',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.Pose.FromString,
                _registered_method=True)
        self.MoveTo = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/MoveTo',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.MoveToRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.CommandJoints = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/CommandJoints',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.JointCommandRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Stop',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.StopRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Enable = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Enable',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Disable = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Disable',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Reset',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.OpenGripper = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/OpenGripper',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.CloseGripper = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/CloseGripper',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.GetGripperState = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/GetGripperState',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.GripperState.FromString,
                _registered_method=True)


class RobotControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveTo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommandJoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenGripper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseGripper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGripperState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.HealthRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.HealthReply.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.RobotState.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.StreamStateRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.RobotState.SerializeToString,
            ),
            'GetPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPose,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.Pose.SerializeToString,
            ),
            'MoveTo': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveTo,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.MoveToRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'CommandJoints': grpc.unary_unary_rpc_method_handler(
                    servicer.CommandJoints,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.JointCommandRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.StopRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'Enable': grpc.unary_unary_rpc_method_handler(
                    servicer.Enable,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'Disable': grpc.unary_unary_rpc_method_handler(
                    servicer.Disable,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'OpenGripper': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenGripper,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'CloseGripper': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseGripper,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'GetGripperState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGripperState,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.GripperState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sawyer.control.v1.RobotControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sawyer.control.v1.RobotControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Health',
            sawyer__control_dot_v1_dot_control__pb2.HealthRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/GetState',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sawyer.control.v1.RobotControl/StreamState',
            sawyer__control_dot_v1_dot_control__pb2.StreamStateRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/GetPose',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/MoveTo',
            sawyer__control_dot_v1_dot_control__pb2.MoveToRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommandJoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/CommandJoints',
            sawyer__control_dot_v1_dot_control__pb2.JointCommandRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Stop',
            sawyer__control_dot_v1_dot_control__pb2.StopRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Enable',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Disable',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Reset',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenGripper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/OpenGripper',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseGripper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/CloseGripper',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGripperState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/GetGripperState',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.GripperState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ForceTorqueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReading = channel.unary_unary(
                '/sawyer.control.v1.ForceTorque/GetReading',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.FromString,
                _registered_method=True)
        self.StreamReadings = channel.unary_stream(
                '/sawyer.control.v1.ForceTorque/StreamReadings',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.StreamReadingsRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.FromString,
                _registered_method=True)
        self.Zero = channel.unary_unary(
                '/sawyer.control.v1.ForceTorque/Zero',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)


class ForceTorqueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReadings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Zero(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForceTorqueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReading': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReading,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.SerializeToString,
            ),
            'StreamReadings': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamReadings,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.StreamReadingsRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.SerializeToString,
            ),
            'Zero': grpc.unary_unary_rpc_method_handler(
                    servicer.Zero,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sawyer.control.v1.ForceTorque', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sawyer.control.v1.ForceTorque', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForceTorque(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorque/GetReading',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReadings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sawyer.control.v1.ForceTorque/StreamReadings',
            sawyer__control_dot_v1_dot_control__pb2.StreamReadingsRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Zero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorque/Zero',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ForceTorqueConfigStub(object):
    """Config plane: the sensor's HTTP settings, persisted in the device across
    reboots. Separate from ForceTorque because it is a different transport and a
    different latency class. Mechanism only - the bridge applies no defaults and
    writes nothing unless called. Network settings are deliberately absent.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentity = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/GetIdentity',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtIdentity.FromString,
                _registered_method=True)
        self.GetScaling = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/GetScaling',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSlotRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtScaling.FromString,
                _registered_method=True)
        self.GetDeviceStatus = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/GetDeviceStatus',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtDeviceStatus.FromString,
                _registered_method=True)
        self.GetConfiguration = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/GetConfiguration',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSlotRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtConfiguration.FromString,
                _registered_method=True)
        self.ListConfigurations = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/ListConfigurations',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtConfigurationList.FromString,
                _registered_method=True)
        self.WriteConfiguration = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/WriteConfiguration',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtWriteConfigurationRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtConfiguration.FromString,
                _registered_method=True)
        self.SetToolTransform = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetToolTransform',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtToolTransformRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtConfiguration.FromString,
                _registered_method=True)
        self.SelectConfiguration = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SelectConfiguration',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSlotRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
                _registered_method=True)
        self.GetSettings = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/GetSettings',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
                _registered_method=True)
        self.SetFilter = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetFilter',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtFilterRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
                _registered_method=True)
        self.SetPeakLogging = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetPeakLogging',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
                _registered_method=True)
        self.SetBiasVector = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetBiasVector',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtBiasRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
                _registered_method=True)
        self.ClearBias = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/ClearBias',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
                _registered_method=True)
        self.GetCommunications = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/GetCommunications',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
                _registered_method=True)
        self.SetRate = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetRate',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtRateRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
                _registered_method=True)
        self.SetBufferRecords = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetBufferRecords',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtBufferRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
                _registered_method=True)
        self.SetRdtEnabled = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetRdtEnabled',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
                _registered_method=True)
        self.SetEthernetIpEnabled = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetEthernetIpEnabled',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
                _registered_method=True)
        self.GetMonitorConditions = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/GetMonitorConditions',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtMonitorConditions.FromString,
                _registered_method=True)
        self.SetMonitorCondition = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetMonitorCondition',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtMonitorConditionRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtMonitorCondition.FromString,
                _registered_method=True)
        self.SetMonitorConditionsEnabled = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/SetMonitorConditionsEnabled',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
                _registered_method=True)
        self.GetPeaks = channel.unary_unary(
                '/sawyer.control.v1.ForceTorqueConfig/GetPeaks',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtPeaks.FromString,
                _registered_method=True)


class ForceTorqueConfigServicer(object):
    """Config plane: the sensor's HTTP settings, persisted in the device across
    reboots. Separate from ForceTorque because it is a different transport and a
    different latency class. Mechanism only - the bridge applies no defaults and
    writes nothing unless called. Network settings are deliberately absent.
    """

    def GetIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScaling(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConfigurations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetToolTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFilter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPeakLogging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBiasVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearBias(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBufferRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRdtEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEthernetIpEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitorConditions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMonitorCondition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMonitorConditionsEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeaks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForceTorqueConfigServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtIdentity.SerializeToString,
            ),
            'GetScaling': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScaling,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSlotRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtScaling.SerializeToString,
            ),
            'GetDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatus,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtDeviceStatus.SerializeToString,
            ),
            'GetConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfiguration,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSlotRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtConfiguration.SerializeToString,
            ),
            'ListConfigurations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConfigurations,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtConfigurationList.SerializeToString,
            ),
            'WriteConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteConfiguration,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtWriteConfigurationRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtConfiguration.SerializeToString,
            ),
            'SetToolTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.SetToolTransform,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtToolTransformRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtConfiguration.SerializeToString,
            ),
            'SelectConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectConfiguration,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtSlotRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.SerializeToString,
            ),
            'GetSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSettings,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.SerializeToString,
            ),
            'SetFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFilter,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtFilterRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.SerializeToString,
            ),
            'SetPeakLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPeakLogging,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.SerializeToString,
            ),
            'SetBiasVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBiasVector,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtBiasRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.SerializeToString,
            ),
            'ClearBias': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearBias,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.SerializeToString,
            ),
            'GetCommunications': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunications,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.SerializeToString,
            ),
            'SetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRate,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtRateRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.SerializeToString,
            ),
            'SetBufferRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBufferRecords,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtBufferRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.SerializeToString,
            ),
            'SetRdtEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRdtEnabled,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.SerializeToString,
            ),
            'SetEthernetIpEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEthernetIpEnabled,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtCommunications.SerializeToString,
            ),
            'GetMonitorConditions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitorConditions,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtMonitorConditions.SerializeToString,
            ),
            'SetMonitorCondition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMonitorCondition,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtMonitorConditionRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtMonitorCondition.SerializeToString,
            ),
            'SetMonitorConditionsEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMonitorConditionsEnabled,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtSettings.SerializeToString,
            ),
            'GetPeaks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeaks,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.FtPeaks.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sawyer.control.v1.ForceTorqueConfig', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sawyer.control.v1.ForceTorqueConfig', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForceTorqueConfig(object):
    """Config plane: the sensor's HTTP settings, persisted in the device across
    reboots. Separate from ForceTorque because it is a different transport and a
    different latency class. Mechanism only - the bridge applies no defaults and
    writes nothing unless called. Network settings are deliberately absent.
    """

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/GetIdentity',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScaling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/GetScaling',
            sawyer__control_dot_v1_dot_control__pb2.FtSlotRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtScaling.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/GetDeviceStatus',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtDeviceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/GetConfiguration',
            sawyer__control_dot_v1_dot_control__pb2.FtSlotRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtConfiguration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConfigurations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/ListConfigurations',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtConfigurationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/WriteConfiguration',
            sawyer__control_dot_v1_dot_control__pb2.FtWriteConfigurationRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtConfiguration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetToolTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetToolTransform',
            sawyer__control_dot_v1_dot_control__pb2.FtToolTransformRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtConfiguration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SelectConfiguration',
            sawyer__control_dot_v1_dot_control__pb2.FtSlotRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/GetSettings',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetFilter',
            sawyer__control_dot_v1_dot_control__pb2.FtFilterRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPeakLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetPeakLogging',
            sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBiasVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetBiasVector',
            sawyer__control_dot_v1_dot_control__pb2.FtBiasRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearBias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/ClearBias',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/GetCommunications',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetRate',
            sawyer__control_dot_v1_dot_control__pb2.FtRateRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBufferRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetBufferRecords',
            sawyer__control_dot_v1_dot_control__pb2.FtBufferRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRdtEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetRdtEnabled',
            sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEthernetIpEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetEthernetIpEnabled',
            sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtCommunications.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitorConditions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/GetMonitorConditions',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtMonitorConditions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMonitorCondition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetMonitorCondition',
            sawyer__control_dot_v1_dot_control__pb2.FtMonitorConditionRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtMonitorCondition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMonitorConditionsEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/SetMonitorConditionsEnabled',
            sawyer__control_dot_v1_dot_control__pb2.FtEnableRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeaks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorqueConfig/GetPeaks',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.FtPeaks.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CameraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/sawyer.control.v1.Camera/Start',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.CameraRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/sawyer.control.v1.Camera/Stop',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.CameraRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.GetFrame = channel.unary_unary(
                '/sawyer.control.v1.Camera/GetFrame',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.CameraRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.ImageFrame.FromString,
                _registered_method=True)
        self.StreamFrames = channel.unary_stream(
                '/sawyer.control.v1.Camera/StreamFrames',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.CameraStreamRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.ImageFrame.FromString,
                _registered_method=True)


class CameraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.CameraRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.CameraRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'GetFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFrame,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.CameraRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.ImageFrame.SerializeToString,
            ),
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.CameraStreamRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.ImageFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sawyer.control.v1.Camera', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sawyer.control.v1.Camera', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Camera(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.Camera/Start',
            sawyer__control_dot_v1_dot_control__pb2.CameraRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.Camera/Stop',
            sawyer__control_dot_v1_dot_control__pb2.CameraRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.Camera/GetFrame',
            sawyer__control_dot_v1_dot_control__pb2.CameraRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.ImageFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sawyer.control.v1.Camera/StreamFrames',
            sawyer__control_dot_v1_dot_control__pb2.CameraStreamRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.ImageFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
