# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sawyer_control.v1 import control_pb2 as sawyer__control_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sawyer_control/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Health',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.HealthRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.HealthReply.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/GetState',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.RobotState.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/sawyer.control.v1.RobotControl/StreamState',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.StreamStateRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.RobotState.FromString,
                _registered_method=True)
        self.GetPose = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/GetPose',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.Pose.FromString,
                _registered_method=True)
        self.MoveTo = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/MoveTo',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.MoveToRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.CommandJoints = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/CommandJoints',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.JointCommandRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.StartSequence = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/StartSequence',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.SequenceRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.Operation.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/GetOperation',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.OperationRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Stop',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.StopRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Enable = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Enable',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Disable = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Disable',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/Reset',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.OpenGripper = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/OpenGripper',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.CloseGripper = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/CloseGripper',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)
        self.GetGripperState = channel.unary_unary(
                '/sawyer.control.v1.RobotControl/GetGripperState',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.GripperState.FromString,
                _registered_method=True)


class RobotControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveTo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommandJoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenGripper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseGripper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGripperState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.HealthRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.HealthReply.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.RobotState.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.StreamStateRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.RobotState.SerializeToString,
            ),
            'GetPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPose,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.Pose.SerializeToString,
            ),
            'MoveTo': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveTo,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.MoveToRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'CommandJoints': grpc.unary_unary_rpc_method_handler(
                    servicer.CommandJoints,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.JointCommandRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'StartSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSequence,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.SequenceRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.Operation.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.OperationRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.OperationStatus.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.StopRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'Enable': grpc.unary_unary_rpc_method_handler(
                    servicer.Enable,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'Disable': grpc.unary_unary_rpc_method_handler(
                    servicer.Disable,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'OpenGripper': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenGripper,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'CloseGripper': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseGripper,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
            'GetGripperState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGripperState,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.GripperState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sawyer.control.v1.RobotControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sawyer.control.v1.RobotControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Health',
            sawyer__control_dot_v1_dot_control__pb2.HealthRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/GetState',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sawyer.control.v1.RobotControl/StreamState',
            sawyer__control_dot_v1_dot_control__pb2.StreamStateRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/GetPose',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/MoveTo',
            sawyer__control_dot_v1_dot_control__pb2.MoveToRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommandJoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/CommandJoints',
            sawyer__control_dot_v1_dot_control__pb2.JointCommandRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/StartSequence',
            sawyer__control_dot_v1_dot_control__pb2.SequenceRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/GetOperation',
            sawyer__control_dot_v1_dot_control__pb2.OperationRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Stop',
            sawyer__control_dot_v1_dot_control__pb2.StopRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Enable',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Disable',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/Reset',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenGripper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/OpenGripper',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseGripper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/CloseGripper',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGripperState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.RobotControl/GetGripperState',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.GripperState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ForceTorqueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReading = channel.unary_unary(
                '/sawyer.control.v1.ForceTorque/GetReading',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.FromString,
                _registered_method=True)
        self.StreamReadings = channel.unary_stream(
                '/sawyer.control.v1.ForceTorque/StreamReadings',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.StreamReadingsRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.FromString,
                _registered_method=True)
        self.Zero = channel.unary_unary(
                '/sawyer.control.v1.ForceTorque/Zero',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
                _registered_method=True)


class ForceTorqueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReadings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Zero(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForceTorqueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReading': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReading,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.SerializeToString,
            ),
            'StreamReadings': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamReadings,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.StreamReadingsRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.SerializeToString,
            ),
            'Zero': grpc.unary_unary_rpc_method_handler(
                    servicer.Zero,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.Empty.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.CommandResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sawyer.control.v1.ForceTorque', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sawyer.control.v1.ForceTorque', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForceTorque(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorque/GetReading',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReadings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sawyer.control.v1.ForceTorque/StreamReadings',
            sawyer__control_dot_v1_dot_control__pb2.StreamReadingsRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.ForceTorqueReading.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Zero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.ForceTorque/Zero',
            sawyer__control_dot_v1_dot_control__pb2.Empty.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CameraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFrame = channel.unary_unary(
                '/sawyer.control.v1.Camera/GetFrame',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.CameraRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.ImageFrame.FromString,
                _registered_method=True)
        self.StreamFrames = channel.unary_stream(
                '/sawyer.control.v1.Camera/StreamFrames',
                request_serializer=sawyer__control_dot_v1_dot_control__pb2.CameraStreamRequest.SerializeToString,
                response_deserializer=sawyer__control_dot_v1_dot_control__pb2.ImageFrame.FromString,
                _registered_method=True)


class CameraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFrame,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.CameraRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.ImageFrame.SerializeToString,
            ),
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=sawyer__control_dot_v1_dot_control__pb2.CameraStreamRequest.FromString,
                    response_serializer=sawyer__control_dot_v1_dot_control__pb2.ImageFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sawyer.control.v1.Camera', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sawyer.control.v1.Camera', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Camera(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sawyer.control.v1.Camera/GetFrame',
            sawyer__control_dot_v1_dot_control__pb2.CameraRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.ImageFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sawyer.control.v1.Camera/StreamFrames',
            sawyer__control_dot_v1_dot_control__pb2.CameraStreamRequest.SerializeToString,
            sawyer__control_dot_v1_dot_control__pb2.ImageFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
